import mongoose, { Schema, Document } from 'mongoose';

export interface ITask extends Document {
  tripId: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  dueDate?: Date;
  completed: boolean;
  category: 'packing' | 'booking' | 'preparation' | 'general';
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const TaskSchema = new Schema(
  {
    tripId: {
      type: Schema.Types.ObjectId,
      ref: 'Trip',
      required: true,
      index: true,
    },
    title: { type: String, required: true },
    description: String,
    dueDate: Date,
    completed: { type: Boolean, default: false },
    category: {
      type: String,
      enum: ['packing', 'booking', 'preparation', 'general'],
      default: 'general',
    },
    isAutoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

export const Task = mongoose.model<ITask>('Task', TaskSchema);
