import { Task } from '@/models/Task';
import mongoose from 'mongoose';

interface TaskSuggestion {
  title: string;
  category: 'packing' | 'booking' | 'preparation' | 'general';
  dueDate?: Date;
}

export class TaskSuggestionService {
  async generateSuggestedTasks(tripId: string): Promise<TaskSuggestion[]> {
    const suggestions: TaskSuggestion[] = [];
    const objectId = new mongoose.Types.ObjectId(tripId);

    try {
      // Check for flights
      const flights = await this.getFlightsByTripId(tripId);
      if (flights.length > 0) {
        suggestions.push(
          {
            title: 'Check in online for flights',
            category: 'preparation',
            dueDate: new Date(flights[0].departureTime.getTime() - 24 * 60 * 60 * 1000),
          },
          {
            title: 'Download boarding passes',
            category: 'preparation',
            dueDate: new Date(flights[0].departureTime.getTime() - 12 * 60 * 60 * 1000),
          }
        );
      }

      // Check for accommodation
      const accommodations = await this.getAccommodationsByTripId(tripId);
      if (accommodations.length > 0) {
        accommodations.forEach((acc) => {
          suggestions.push({
            title: `Confirm reservation at ${acc.hotelName}`,
            category: 'booking',
            dueDate: new Date(acc.checkInDate.getTime() - 3 * 24 * 60 * 60 * 1000),
          });
        });
      }

      // Universal suggestions
      suggestions.push(
        {
          title: 'Pack luggage',
          category: 'packing',
        },
        {
          title: 'Check weather forecast',
          category: 'preparation',
        },
        {
          title: 'Set up travel insurance',
          category: 'booking',
        }
      );

      return suggestions;
    } catch (error) {
      console.error('Error generating task suggestions:', error);
      return suggestions;
    }
  }

  async createSuggestedTasks(tripId: string): Promise<void> {
    try {
      const suggestions = await this.generateSuggestedTasks(tripId);
      const objectId = new mongoose.Types.ObjectId(tripId);

      for (const suggestion of suggestions) {
        const existingTask = await Task.findOne({
          tripId: objectId,
          title: suggestion.title,
          isAutoGenerated: true,
        });

        if (!existingTask) {
          await Task.create({
            tripId: objectId,
            ...suggestion,
            isAutoGenerated: true,
          });
        }
      }
    } catch (error) {
      console.error('Error creating suggested tasks:', error);
    }
  }

  private async getFlightsByTripId(tripId: string) {
    // TODO: Import and use Flight model
    return [];
  }

  private async getAccommodationsByTripId(tripId: string) {
    // TODO: Import and use Accommodation model
    return [];
  }
}
